development:
  adapter: postgresql
  database: myrecipes_development
  username: postgres
  password: garciamercado1997
  host: localhost
  prepared_statements: false

test:
  adapter: postgresql
  database: myrecipes_test
  username: postgres
  password: garciamercado1997
  host: localhost
  prepared_statements: false
